apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: py-http-ingress
spec:
  rules:
  - host: kub-worker1.cs2.netpoint-dc.com
    http:
      paths:
      - backend:
          serviceName: py-http-service
          servicePort: 80
  - host: kub-worker2.cs2.netpoint-dc.com
    http:
      paths:
      - backend:
          serviceName: py-http-service
          servicePort: 80