variables:
    LATEST_VER: pogossian/pyhttp:latest
    MAJOR_VER: pogossian/pyhttp:1
    MINOR_VER: pogossian/pyhttp:1.0
    BUGFIX_VER: pogossian/pyhttp:1.0.2
  
stages:
- Build image
- Push to Docker Hub
- Deploy

build image:
    stage: Build image
    script:
    - docker build -t $LATEST_VER -t $MAJOR_VER -t $MINOR_VER -t $BUGFIX_VER .
  

push image:
    stage: Push to Docker Hub
    only:
    - master
    script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker push $LATEST_VER && docker image rm $LATEST_VER
    - docker push $MAJOR_VER && docker image rm $MAJOR_VER
    - docker push $MINOR_VER && docker image rm $MINOR_VER
    - docker push $BUGFIX_VER && docker image rm $BUGFIX_VER
    
      

deploy on k8s:
    stage: Deploy
    before_script:
    - echo 'before_script'
    script:
    - printenv