# - hosts: localhost
#   connection: local
#   become: yes
#   gather_facts: false
#   vars:
#     PROJECT_NAME: "{{ lookup('env','CI_PROJECT_TITLE') }}"
#     CEPH_MONITORS: 10.120.29.114:6789,10.120.28.174:6789,10.120.29.159:6789:/
#     CEPH_USER: "{{ lookup('env','CEPH_USER') }}"
#     CEPH_SECRET: "{{ lookup('env','CEPH_SECRET') }}"
#     MOUNT_DIRECTORY: /mnt/cephfs/
#     PV_PATH: pvc-volumes/kubernetes/kubernetes-dynamic-pvc-3e7cfd79-29c6-11ea-a936-9e006f2f84c4/
#   tasks:
#     - name: Mount CephFS
#       mount:
#         path: "{{ MOUNT_DIRECTORY }}"
#         src: "{{ CEPH_MONITORS }}"
#         fstype: ceph
#         opts: "{{ 'name=' + CEPH_USER + ',secret=' + CEPH_SECRET}}"
#         state: mounted

#     - name: Copy static directory to CephFS
#       copy:
#         src: static/
#         dest: "{{ MOUNT_DIRECTORY + PV_PATH }}"
#         remote_src: yes
    
#     - name: Unmount CephFS
#       mount:
#         path: "{{ MOUNT_DIRECTORY }}"
#         state: absent


- hosts: kub-master
  remote_user: administrator
  become: no
  gather_facts: false
  vars:
    PROJECT_NAME: "{{ lookup('env','CI_PROJECT_TITLE') }}"
    PROJECT_BRANCH: "{{ lookup('env','CI_COMMIT_BRANCH') }}"
  tasks:
    - name: Copy k8s yamls to master node
      copy:
        src: .kube/
        dest: "{{ PROJECT_NAME + '_' + PROJECT_BRANCH }}"
    
    - name: Applying configs
      command: kubectl apply -f "{{ PROJECT_NAME + '_' + PROJECT_BRANCH }}"
      


