# - hosts: localhost
#   connection: local
#   become: yes
#   gather_facts: false
#   vars:
#     CEPH_MONITORS: 10.120.29.114:6789,10.120.28.174:6789,10.120.29.159:6789:/
#     CEPH_USER: "{{ lookup('env','CEPH_USER') }}"
#     CEPH_SECRET: "{{ lookup('env','CEPH_SECRET') }}"
#     MOUNT_DIRECTORY: /mnt/cephfs/
#     PV_PATH: pvc-volumes/kubernetes/kubernetes-dynamic-pvc-683795e9-30d6-11ea-a089-aa3b012fb514/
#   tasks:
#     - name: Mount CephFS
#       mount:
#         path: "{{ MOUNT_DIRECTORY }}"
#         src: "{{ CEPH_MONITORS }}"
#         fstype: ceph
#         opts: "{{ 'name=' + CEPH_USER + ',secret=' + CEPH_SECRET}}"
#         state: mounted

#     - name: Copy static directory to CephFS
#       copy:
#         src: static/
#         dest: "{{ MOUNT_DIRECTORY + PV_PATH }}"
#         remote_src: yes
    
#     - name: Unmount CephFS
#       mount:
#         path: "{{ MOUNT_DIRECTORY }}"
#         state: absent


- hosts: kub-master
  remote_user: administrator
  become: no
  gather_facts: false
  vars:
    PROJECT_NAME: "{{ lookup('env','CI_PROJECT_TITLE') }}"
    PROJECT_BRANCH: "{{ lookup('env','CI_COMMIT_BRANCH') }}"
    CONF_DIR: .kube/
  tasks:
    - name: Checking if develop branch
      set_fact:
        CONF_DIR: .kube_develop/
      when: PROJECT_BRANCH == "develop"


    - name: Copy k8s yamls to master node
      copy:
        src: CONF_DIR
        dest: "{{ PROJECT_NAME + '_' + PROJECT_BRANCH }}"
    
    - name: Applying configs
      command: kubectl apply -f "{{ PROJECT_NAME + '_' + PROJECT_BRANCH }}"
      


